### PR TITLE
fix: no longer generate .nuxt/tailwind.config.cjs

### LINKED ISSUE #589: Editor Support is not working under certain circumstances
It turned out, that using `.nuxt/tailwind.config.cjs` for the VSCode plugin does not always work and is not recommended. See https://github.com/tailwindlabs/tailwindcss-intellisense/issues/663#issuecomment-1316788128.
The plugin expects a non-resolved version of the config in the CommonJS format. That means that either we need to change the documentation to only recommend using CommonJS for the config, or we change the file to not include the resolved config, but only the raw config, transpiled to CJS.

### PR DESCRIPTION
**Pull request by P4sca1**
Resolves #589

The file is no longer needed for editor support, because as of tailwindcss 3.3.0 and [@tailwindcss/language-server@v0.0.13](https://github.com/tailwindlabs/tailwindcss-intellisense/releases/tag/%40tailwindcss%2Flanguage-server%40v0.0.13), ESM and TS config files are supported out of the box.

I also updated the editor support section in the docs to the simplified setup instructions.

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -157,24 +157,11 @@ export default defineNuxtModule<ModuleOptions>({
...
-      filename: 'tailwind.config.cjs',
-      getContents: () => `module.exports = ${JSON.stringify(resolvedConfig, null, 2)}`,
-      write: true
-    })
-
     // Expose resolved tailwind config as an alias
     // https://tailwindcss.com/docs/configuration/#referencing-in-javascript
     if (moduleOptions.exposeConfig) {
-      createTemplates(resolvedConfig, moduleOptions.exposeLevel, nuxt)
+      const resolveConfig = await import('tailwindcss/resolveConfig.js').then(r => r.default || r)
```
Comment (ineshbose) [inline src/module.ts:163]: I was anyway thinking that we can remove the dynamic import here (is there a reason for it @Atinux ?) and do

```ts
// @ts-expect-error (if TS complains)
import resolveConfig from "tailwindcss/resolveConfig.js"
```

in fact, this import could just be in `utils.ts` and usage added to `createTemplates` function.

**Comment by ineshbose** [comment]
Also, would you be able to see why the test is failing? I see that it may have something to do with `test/fixture/basic/override-tailwind.config.js` (overriding `content` through a function is allowed as the module uses [defu](https://github.com/unjs/defu), but keep in mind that functions do not get serialized into the files)

File: src/module.ts (hunk 1 above)
Comment (ineshbose) [reply src/module.ts:163]: Btw, we may still want to provide a hook with resolved config if devs may need a `.cjs` (https://github.com/nuxt-modules/tailwindcss/pull/655#issuecomment-1510349845)
