### PR TITLE
fix(exposeConfig): named exports in mjs for tree-shaking

### LINKED ISSUE #481: exposeConfig with specific part is undefined
### Version
@nuxtjs/tailwindcss: **5.0.3**
nuxt: **2.15.8**

### Steps to reproduce

Set `exposeConfig` to `true` in `nuxt.config.js`
```js
export default {
  tailwindcss: {
    exposeConfig: true
  }
}
```

Import `theme` from configuration in component.
```js
import { theme } from '#tailwind-config'
```

### What is Expected?
Expecting `theme` to be defined.

### What is actually happening?
`theme` is undefined.

When importing the full configuration, I can get the `theme` field.

### PR DESCRIPTION
**Pull request by ineshbose**
Resolve #481

### CODE REVIEW

**Comment by danielroe** [comment]
I don't believe this would resolve that issue. The issue that people have raised is that the tailwind config is exposed as a single default export: https://github.com/nuxt-modules/tailwindcss/issues/481#issuecomment-1216461567.

**Comment by danielroe** [comment]
What makes you think that this needs to be written? I don't believe that is required or desirable (it has a negative performance impact).

You are right that the docs need to be updated (or the virtual module needs to also have named exports).

**Comment by danielroe** [comment]
It doesn't need to be written to disk; it's a virtual file that will still be included in the build.

**Comment by ineshbose** [comment]
My apologies - I wasn't aware of that functionality!

**Comment by danielroe** [comment]
No problem at all! Nuxt 3 makes extensive use of virtual modules for most source files it provides (as distinct from type declarations, which we write to disk so IDEs are aware of them).

File: src/module.ts [hunk 1]
```diff
@@ -150,7 +150,7 @@ export default defineNuxtModule<ModuleOptions>({
     if (moduleOptions.exposeConfig) {
       const template = addTemplate({
         filename: 'tailwind.config.mjs',
-        getContents: () => `export default ${JSON.stringify(resolvedConfig, null, 2)}`
+        getContents: () => `${Object.entries(resolvedConfig).map(([k, v]) => `export const ${k} = ${JSON.stringify(v, null, 2)}`).join('\n')}\nexport default ${JSON.stringify(resolvedConfig, null, 2)}`
```
Comment (danielroe) [inline src/module.ts:153]: Rather than include the config twice, can we reuse the named exports to produce the default export?

File: src/module.ts [hunk 2]
```diff
@@ -150,7 +150,7 @@ export default defineNuxtModule<ModuleOptions>({
     if (moduleOptions.exposeConfig) {
       const template = addTemplate({
         filename: 'tailwind.config.mjs',
-        getContents: () => `export default ${JSON.stringify(resolvedConfig, null, 2)}`
+        getContents: () => `${Object.entries(resolvedConfig).map(([k, v]) => `export const ${k} = ${JSON.stringify(v, null, 2)}`).join('\n')}\nexport default {${Object.keys(resolvedConfig)}}`
```
Comment (danielroe) [inline src/module.ts:153]:
```suggestion
        getContents: () => `${Object.entries(resolvedConfig).map(([k, v]) => `export const ${k} = ${JSON.stringify(v, null, 2)}`).join('\n')}\nexport default {${Object.keys(resolvedConfig).join(','}}`
```

File: src/module.ts (hunk 1 above)
Comment (ineshbose) [reply src/module.ts]: A couple of ways I thought to do it - either I assign `Object.entries(resolvedConfig)` to a value or use `.keys` there instead, and if I should have used `.join` - as per you!

**Comment by danielroe** [comment]
perfect 👌 

annoyingly, now we also have to update the declaration file below it so users have intellisense.

**Comment by ineshbose** [comment]
Completely forgot about that. So sorry for the back-and-forths, I'll do that.

**Comment by ineshbose** [comment]
Note - not every export has a type definition, and I'm not sure if `tailwindcssConfig` is an appropriate name!

**Review by danielroe — APPROVED** [review]
perfect - thanks! ❤️

**Review by Atinux — APPROVED** [review]
