### PR TITLE
Fix config not working in nuxt 3.16

### LINKED ISSUE #960: Styling breaks after upgrading to nuxt 3.16
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v23.8.0
- Nuxt Version:     3.16.0
- CLI Version:      3.22.5
- Nitro Version:    2.11.5
- Package Manager:  npm@10.9.2
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

Using tailwind via this module previously worked fine with no module configuration. After upgrading to 3.16 today, I found many of my styles to be missing. 

### Describe the bug

Someone quickly found a solution on the Discord, but it should be noted here in case others run into it. Also, maybe the implementation needs to be updated to support the newest nuxt version.

The fix for me was to add to my nuxt.config.ts:

```
  tailwindcss: {
    config: {
      content: ["./pages/**/*.{vue,js,ts}", "./components/**/*.{vue,js,ts}"],
    },
  },
```

### Additional context

_No response_

### Logs

```shell-script

```

### PR DESCRIPTION
**Pull request by marr**
### 🔗 Linked issue

closes #960

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Fixes tailwindcss config for nuxt 3.16

### CODE REVIEW

File: src/internal-context/load.ts [hunk 1]
```diff
@@ -78,6 +78,7 @@ const createInternalContext = async (moduleOptions: ModuleOptions, nuxt = useNux
         content: {
           files: [
             withSrcDir(`components/**/*${sfcExtensions}`),
+            withSrcDir(`pages/**/*${sfcExtensions}`),
```
Comment (ineshbose) [inline src/internal-context/load.ts:81]: thanks for PR! I'm happy to approve, just wondering what happened with L93 with v3.16

Comment (marr) [reply src/internal-context/load.ts:81]: At a quick glance, I see this change around the pages config in 3.16:
https://github.com/nuxt/nuxt/pull/31090

Maybe the typing around that config property changed?

Comment (ineshbose) [reply src/internal-context/load.ts:81]: Yes, thank you - I noticed this PR but we're checking for `options.dir.pages` which shouldn't change otherwise it would have been breaking change from the core..

Comment (ineshbose) [reply src/internal-context/load.ts:81]: Oh wait - I think I see that `options.pages` is being changed for either being `true` or `undefined` while now an object is allowed. I believe we make appropriate changes there!

Comment (danielroe) [reply src/internal-context/load.ts:81]: it could be:

```ts
...(nuxtOptions.pages !== false && nuxtOptions.pages?.enabled !== false) ? [withSrcDir(`${nuxtOptions.dir?.pages || 'pages'}/**/*${sfcExtensions}`)] : []),
```

Comment (ineshbose) [reply src/internal-context/load.ts:81]: Thanks Daniel! Yep, I was thinking this but I was also wondering if we leave the scanning to Nuxt that'll respect the patterns and we plug into `pages:extend` as well. Could be more narrow, but also improve HMR to pages dir

Comment (danielroe) [reply src/internal-context/load.ts:81]: nice idea.

or you could add it in any case - should be safe

**Comment by ineshbose** [comment]
@marr I've raised a PR to your fork (as I didn't have permission to push). Feel free to review and merge, then we can merge this PR 🙂

File: package.json [hunk 2]
```diff
@@ -62,37 +62,37 @@
     "test:types": "pnpm dev:prepare && tsc --noEmit && nuxi typecheck playground"
   },
   "dependencies": {
-    "@nuxt/kit": "^3.15.1",
```
Comment (leipert) [inline package.json:65]: @ineshbose / @marr Moving this from a dependency to a dev dependency broke the package for us in: https://gitlab.com/gitlab-org/gitlab-services/design.gitlab.com/-/merge_requests/4338 because nuxt@2 doesn't seem to ship `@nuxt/kit` per default. 

It probably should be a peer dependency at least

Comment (danielroe) [reply package.json:65]: `@nuxt/kit` should be an explicit dependency - I did not spot that this PR moved it.

unrelatedly, do you need any help migrating https://gitlab.com/gitlab-org/gitlab-services/design.gitlab.com to nuxt 3?
